### ISSUE TITLE
why almost works

### ISSUE THREAD

**Issue by Kikobeats** [mikker/nextjs-with-tachyons#1]
hey,

What you said that in the documentation? Looks like is totally working 😄 

Did you find any edge case?

**Comment by mikker** [comment]
1. On first render the styles are missing.
2. Compiling with `next build` doesn't work (as far as I remember)

If these problems don't exist anymore then great! 😀

**Comment by Kikobeats** [comment]
It's exists 😂

**Comment by mikker** [comment]
¯\_(ツ)_/¯

**Comment by Kikobeats** [comment]
Thanks; I'm trackings this issues in my boilerplate https://github.com/Kikobeats/next-boilerplatinum/issues 😄
